version: "3.8"

services:
  app:
    build:
      context: .
      ssh:
        - default
      target: server
      args:
        WKHTMLTOPDF_SOURCE: ${WKHTMLTOPDF_SOURCE:-https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.buster_amd64.deb}
        BASE_IMAGE: ${BASE_IMAGE:-ghcr.io/openjksoftware/python-devcontainer:3.10}
        USERNAME: ${CONTAINER_USERNAME:-ContainerUser}
        NODE_VERSION: ${CONTAINER_NODE_VERSION:-16.17.1}
    init: true
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "odoo_web:/var/lib/odoo"
      - "odoo_thirdparty:/odoo/thirdparty"

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${ODOO_DB_PASSWORD:-odoo}
      - POSTGRES_USER=${ODOO_DB_USER:-odoo_user}
    volumes:
      - "db:/var/lib/postgresql/data"
      - "/etc/localtime:/etc/localtime:ro"
      - "./config/postgresql.conf:/etc/postgresql/postgresql.conf"

volumes:
  db:
  odoo_web:
  odoo_thirdparty:
