version: "3.8"

services:
  app:
    build:
      target: devcontainer
      args:
        WKHTMLTOPDF_SOURCE: ${WKHTMLTOPDF_SOURCE}
        BASE_IMAGE: ${BASE_IMAGE}
        USERNAME: ${CONTAINER_USERNAME}
    volumes:
      - ./:/odoo/workspace:cached # Mount vscode Workspace
    cap_add:
      - SYS_PTRACE

volumes:
  vscode_cache:
