version: "3.8"

services:
  app:
    build:
      target: devcontainer
      args:
        SOURCE_CLONE_ARCHIVE: False
    volumes:
      - ./:/odoo/workspace:cached # Mount vscode Workspace
    cap_add:
      - SYS_PTRACE

volumes:
  vscode_cache:
