version: "3.8"

services:
  app:
    build:
      target: devcontainer
    volumes:
      - ./:/odoo/workspace:cached # Mount vscode Workspace
    cap_add:
      - SYS_PTRACE

volumes:
  vscode_cache:
