version: "3.8"

services:
  app:
    build:
      target: devcontainer
      args:
        SOURCE_CLONE_ARCHIVE: False
    command: ""
    volumes:
      - vscode_server:/home/ContainerUser/.vscode-server
      - commandhistory:/home/ContainerUser/.commandhistory
      - pre_commit_cache:/home/ContainerUser/.cache/pre-commit
      - ../:/odoo/godoo # Mount vscode Workspace
    cap_add:
      - SYS_PTRACE

volumes:
  vscode_server:
  commandhistory:
  pre_commit_cache:
