version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      ssh:
        - default
      target: prod
    init: true
    environment:
      - ODOO_DB_HOST=db
      - ODOO_DB_PORT=5432
    extra_hosts:
      - "host.docker.internal:host-gateway" # Link host as dns
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "odoo_web:/var/lib/odoo"
      - "config:/odoo/config"
      - "cache:/var/cache"

  db:
    image: postgres:16-alpine
    environment:
      - TZ=${TZ:-Europe/Berlin}
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${ODOO_DB_PASSWORD}
      - POSTGRES_USER=${ODOO_DB_USER}
    volumes:
      - "db:/var/lib/postgresql/data"
      - "/etc/localtime:/etc/localtime:ro"
      - "../config/postgresql.conf:/etc/postgresql/postgresql.conf"

volumes:
  config:
  cache:
  db:
  odoo_web:
