version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      ssh:
        - default
      target: server
    init: true
    command: ""
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "odoo_web:/var/lib/odoo"
      - "${ODOO_CONF_PATH:-../config}:/config"

  db:
    image: postgres:15-alpine
    environment:
      - TZ=${TZ:-Europe/Berlin}
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${ODOO_DB_PASSWORD:-odoo}
      - POSTGRES_USER=${ODOO_DB_USER:-odoo_user}
    volumes:
      - "db:/var/lib/postgresql/data"
      - "/etc/localtime:/etc/localtime:ro"
      - "../config/postgresql.conf:/etc/postgresql/postgresql.conf"

  cups:
    build:
      context: cups
      dockerfile: Dockerfile.cups

volumes:
  db:
  odoo_web:
