version: "3.8"

services:
  app:
    build:
      target: devcontainer
      args:
        SOURCE_CLONE_ARCHIVE: False
    command: ""
    volumes:
      - vscode_server:/home/ContainerUser/.vscode-server
      - commandhistory:/home/ContainerUser/.commandhistory
      - pre_commit_cache:/home/ContainerUser/.cache/pre-commit
      - ../:/odoo/godoo_workspace # Mount vscode Workspace
      - venv:/odoo/venv
    cap_add:
      - SYS_PTRACE

  cups:
    build:
      context: cups
      dockerfile: Dockerfile.cups

volumes:
  venv:
  vscode_server:
  commandhistory:
  pre_commit_cache:
