version: "3.8"

services:
  cups:
    networks:
      - default
      - traefik
    labels:
      - traefik.enable=true

      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-cups.service=${COMPOSE_PROJECT_NAME}-cups
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-cups.entrypoints=websecure
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-cups.rule=HostRegexp(`cups-${TRAEFIK_HOST_REGEX}`)
      - traefik.http.services.${COMPOSE_PROJECT_NAME}-cups.loadbalancer.server.port=631

networks:
  traefik:
    external: true
