version: "3.8"

services:
  app:
    networks:
      - default
      - traefik
    environment:
      - ODOO_DB_HOST=db.${COMPOSE_PROJECT_NAME}_default # To avoid conflicts with other Odoo instances through the traefik network
    labels:
      - traefik.enable=true

      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=HostRegexp(`${TRAEFIK_HOST_REGEX}`)
      - traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80

networks:
  traefik:
    external: true
