services:
  app:
    networks:
      - default
      - traefik
    labels:
      - traefik.enable=true

      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=HostRegexp(`${TRAEFIK_HOST_REGEX}`)
      - traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80

networks:
  traefik:
    external: true
