services:
  app:
    build:
      target: devcontainer
    command: ""
    volumes:
      - commandhistory:/home/ContainerUser/.commandhistory
      - ../:/odoo/godoo_workspace # Mount vscode Workspace
      - ../config:/odoo/config # Mount config folder
    cap_add:
      - SYS_PTRACE

  cups:
    build:
      context: cups

volumes:
  commandhistory:
