#!/bin/bash
_godoo_completion() {
    local IFS=$'
'
    COMPREPLY=( $( env COMP_WORDS="${COMP_WORDS[*]}" \
                   COMP_CWORD=$COMP_CWORD \
                   _GODOO_COMPLETE=complete_bash $1 ) )
    return 0
}
