name: Publish

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  release:
    types: [created]
  workflow_call:
    secrets:
      PYPI_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Publish to Pypi
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Install Hatch
        uses: pypa/hatch@install

      - name: Build and publish
        env:
          HATCH_INDEX_AUTH: ${{ secrets.PYPI_TOKEN }}
        run: |
          git fetch --tags
          VERSION=$(git describe --tags --abbrev=0)
          echo "Publishing version $VERSION"
          hatch version $VERSION
          hatch build
          hatch publish
