name: Publish

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  release:
    types: [created]
  workflow_call:
    secrets:
      PYPI_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Publish to Pypi
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Add Poetry Version for __init__.py
        run: poetry self add poetry-bumpversion
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: "poetry"
      - name: Build and publish
        run: |
          poetry version $(git describe --tags --abbrev=0)
          poetry build
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish
